In [1]:
!pip -q install faiss-cpu
import pandas as pd
import numpy as np
import faiss

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.3/31.3 MB 15.9 MB/s eta 0:00:00

In [2]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/amazon.csv')
data

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,₹379,₹919,59%,4,"1,090",SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p...",https://m.media-amazon.com/images/I/41fDdRtjfx...,https://www.amazon.in/Noir-Aqua-Spanner-Purifi...
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,280","₹3,045",25%,4.1,"4,118","230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri...",https://m.media-amazon.com/images/I/41gzDxk4+k...,https://www.amazon.in/Prestige-Delight-PRWO-1-...
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...","₹2,219","₹3,080",28%,3.6,468,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Bajaj-RX-10-2000-Watt-Co...
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...","₹1,399","₹1,890",26%,4,"8,031",Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Havells-Ventilair-230mm-...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,"₹2,863","₹3,690",22%,4.3,"6,987","Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Borosil-Jumbo-1000-Watt-...

In [3]:
data = data[['product_name', "category","rating","review_title"]].drop_duplicates().reset_index(drop=True)
data

,product_name,category,rating,review_title
0,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,4.2,"Satisfied,Charging is really fast,Value for mo..."
1,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,4.0,"A Good Braided Cable for Your Type C Device,Go..."
2,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,3.9,"Good speed for earlier versions,Good Product,W..."
3,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,4.2,"Good product,Good one,Nice,Really nice product..."
4,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,4.2,"As good as original,Decent,Good one for second..."
...,...,...,...,...
1343,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,4,"Received the product without spanner,Excellent..."
1344,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4.1,"ok,everything was good couldn't return bcoz I ..."
1345,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...",3.6,"very good,Work but front melt after 2 month,Go..."
1346,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...",4,"Fan Speed is slow,Good quality,Good product,go..."
1347,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4.3,"Works perfect,Ok good product,Nice Product. Re..."

In [4]:
data.isnull().any()

product_name    False
category        False
rating          False
review_title    False
dtype: bool

In [5]:
data = pd.DataFrame(data)

In [6]:
data

,product_name,category,rating,review_title
0,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,4.2,"Satisfied,Charging is really fast,Value for mo..."
1,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,4.0,"A Good Braided Cable for Your Type C Device,Go..."
2,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,3.9,"Good speed for earlier versions,Good Product,W..."
3,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,4.2,"Good product,Good one,Nice,Really nice product..."
4,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,4.2,"As good as original,Decent,Good one for second..."
...,...,...,...,...
1343,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,4,"Received the product without spanner,Excellent..."
1344,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4.1,"ok,everything was good couldn't return bcoz I ..."
1345,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...",3.6,"very good,Work but front melt after 2 month,Go..."
1346,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...",4,"Fan Speed is slow,Good quality,Good product,go..."
1347,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4.3,"Works perfect,Ok good product,Nice Product. Re..."

In [8]:
data['all_details'] = data['product_name'] + " " + data['category'] +" " + data['rating'] +" " + data['review_title']

In [9]:
data

,product_name,category,rating,review_title,all_details
0,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,4.2,"Satisfied,Charging is really fast,Value for mo...",Wayona Nylon Braided USB to Lightning Fast Cha...
1,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,4.0,"A Good Braided Cable for Your Type C Device,Go...",Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,3.9,"Good speed for earlier versions,Good Product,W...",Sounce Fast Phone Charging Cable & Data Sync U...
3,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,4.2,"Good product,Good one,Nice,Really nice product...",boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,4.2,"As good as original,Decent,Good one for second...",Portronics Konnect L 1.2M Fast Charging 3A 8 P...
...,...,...,...,...,...
1343,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen|Kitchen&HomeAppliances|WaterPurif...,4,"Received the product without spanner,Excellent...",Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...
1344,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4.1,"ok,everything was good couldn't return bcoz I ...",Prestige Delight PRWO Electric Rice Cooker (1 ...
1345,Bajaj Majesty RX10 2000 Watts Heat Convector R...,"Home&Kitchen|Heating,Cooling&AirQuality|RoomHe...",3.6,"very good,Work but front melt after 2 month,Go...",Bajaj Majesty RX10 2000 Watts Heat Convector R...
1346,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,"Home&Kitchen|Heating,Cooling&AirQuality|Fans|E...",4,"Fan Speed is slow,Good quality,Good product,go...",Havells Ventil Air DSP 230mm Exhaust Fan (Pist...
1347,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen|Kitchen&HomeAppliances|SmallKitch...,4.3,"Works perfect,Ok good product,Nice Product. Re...",Borosil Jumbo 1000-Watt Grill Sandwich Maker (...

In [10]:
course_corpus = data['all_details']

In [11]:
course_corpus

0       Wayona Nylon Braided USB to Lightning Fast Cha...
1       Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
2       Sounce Fast Phone Charging Cable & Data Sync U...
3       boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
4       Portronics Konnect L 1.2M Fast Charging 3A 8 P...
                              ...
1343    Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...
1344    Prestige Delight PRWO Electric Rice Cooker (1 ...
1345    Bajaj Majesty RX10 2000 Watts Heat Convector R...
1346    Havells Ventil Air DSP 230mm Exhaust Fan (Pist...
1347    Borosil Jumbo 1000-Watt Grill Sandwich Maker (...
Name: all_details, Length: 1348, dtype: object

In [13]:
  from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
vectorizer = TfidfVectorizer(analyzer='char_wb', ngram_range=(3,3), min_df=5)
X = vectorizer.fit_transform(course_corpus)
X = np.float32(X.toarray())

In [17]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.03340738, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.08462479, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [18]:
index = faiss.IndexFlatL2(X.shape[1])
index.add(X)

In [19]:
ip=input("Enter the product name: ")

Enter the product name: computer

In [20]:
ip

'computer'

In [22]:
search_text = [f"{ip}"]
search_text_vector = vectorizer.transform(search_text)
search_text_vector_array = np.float32(search_text_vector.toarray())

distances, indices = index.search(search_text_vector_array, 5)

In [23]:
indices[0]

array([820, 684, 773,  30, 154])

In [25]:
product_names = [data['product_name'][indices[0][i]] for i in range(len(indices[0]))]
category_names = [data['category'][indices[0][i]] for i in range(len(indices[0]))]
rating_names = [data['rating'][indices[0][i]] for i in range(len(indices[0]))]
review_names = [data['review_title'][indices[0][i]] for i in range(len(indices[0]))]

In [26]:
product_names=pd.DataFrame(product_names)
category_names=pd.DataFrame(category_names)
rating_names=pd.DataFrame(rating_names)
review_names=pd.DataFrame(review_names)

In [27]:
final = pd.concat([product_names, category_names, rating_names, review_names], axis=1)

# Rename the columns
final.columns = ['product_name', 'category', 'rating', 'review_title']

In [28]:
final

,product_name,category,rating,review_title
0,ZEBRONICS Zeb-100HB 4 Ports USB Hub for Laptop...,Computers&Accessories|Accessories&Peripherals|...,3.7,"Good,Quality and compatibility are justified t..."
1,STRIFF Laptop Stand Adjustable Laptop Computer...,Computers&Accessories|Accessories&Peripherals|...,4.2,"Decent quality product for the price,Nice prod..."
2,IT2M Designer Mouse Pad for Laptop/Computer (9...,Computers&Accessories|Accessories&Peripherals|...,4.3,"Very nice quality,Good one for office use,Good..."
3,AmazonBasics USB 2.0 - A-Male to A-Female Exte...,Computers&Accessories|Accessories&Peripherals|...,4.5,"Nice,good,Paisa vassol,Sturdy and long.,Good f..."
4,GENERIC Ultra-Mini Bluetooth CSR 4.0 USB Dongl...,Computers&Accessories|NetworkingDevices|Networ...,3.4,Install CSR Driver For Advanced Features + Sta...

In [29]:
final = final.sort_values(by='rating', ascending=False)

In [30]:
final

,product_name,category,rating,review_title
3,AmazonBasics USB 2.0 - A-Male to A-Female Exte...,Computers&Accessories|Accessories&Peripherals|...,4.5,"Nice,good,Paisa vassol,Sturdy and long.,Good f..."
2,IT2M Designer Mouse Pad for Laptop/Computer (9...,Computers&Accessories|Accessories&Peripherals|...,4.3,"Very nice quality,Good one for office use,Good..."
1,STRIFF Laptop Stand Adjustable Laptop Computer...,Computers&Accessories|Accessories&Peripherals|...,4.2,"Decent quality product for the price,Nice prod..."
0,ZEBRONICS Zeb-100HB 4 Ports USB Hub for Laptop...,Computers&Accessories|Accessories&Peripherals|...,3.7,"Good,Quality and compatibility are justified t..."
4,GENERIC Ultra-Mini Bluetooth CSR 4.0 USB Dongl...,Computers&Accessories|NetworkingDevices|Networ...,3.4,Install CSR Driver For Advanced Features + Sta...

In [31]:
from textblob import TextBlob

final['sentiment'] = final['review_title'].apply(lambda x: 'Positive review' if TextBlob(x).sentiment.polarity > 0 else 'Negative review')

In [32]:
final

,product_name,category,rating,review_title,sentiment
3,AmazonBasics USB 2.0 - A-Male to A-Female Exte...,Computers&Accessories|Accessories&Peripherals|...,4.5,"Nice,good,Paisa vassol,Sturdy and long.,Good f...",Positive review
2,IT2M Designer Mouse Pad for Laptop/Computer (9...,Computers&Accessories|Accessories&Peripherals|...,4.3,"Very nice quality,Good one for office use,Good...",Positive review
1,STRIFF Laptop Stand Adjustable Laptop Computer...,Computers&Accessories|Accessories&Peripherals|...,4.2,"Decent quality product for the price,Nice prod...",Positive review
0,ZEBRONICS Zeb-100HB 4 Ports USB Hub for Laptop...,Computers&Accessories|Accessories&Peripherals|...,3.7,"Good,Quality and compatibility are justified t...",Positive review
4,GENERIC Ultra-Mini Bluetooth CSR 4.0 USB Dongl...,Computers&Accessories|NetworkingDevices|Networ...,3.4,Install CSR Driver For Advanced Features + Sta...,Positive review

In [34]:
final.to_excel('product_recommendation.xlsx', index=False)

In [35]:
import pickle
import faiss

# Save TF-IDF Vectorizer
with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

# Save FAISS index
faiss.write_index(index, "faiss_index.idx")

In [36]:
from google.colab import files
files.download("vectorizer.pkl")
files.download("faiss_index.idx")

In [37]:
import pickle

with open("course_corpus.pkl", "wb") as f:
    pickle.dump(course_corpus, f)

In [39]:
files.download("course_corpus.pkl")